//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarMobile {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolarMobile.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This software was developed with educational purposes only. However, it should give you a decent estimate on the viability of photovoltaic systems, especially if you live close to Canada, United States, Russia, Japan, South Africa, Australia, Brazil, Mexico, United Kingdom, South Korea, Turkey, Indonesia, Germany, France, China, Italy or India. You should take into account that energy regulations vary a lot from country to country and professional help should be sought if you are interested in investing..
        /// </summary>
        internal static string aboutMessage {
            get {
                return ResourceManager.GetString("aboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cash Flux.
        /// </summary>
        internal static string cashFluxTitle {
            get {
                return ResourceManager.GetString("cashFluxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a For the financial analysis, we are considering the currency and total costs of solar systems in COUNTRY (CURRENCY). The final cost of your photovoltaic system should be $ TOTALCOST. A cash flux bellow will illustrate the financial return for the next 25 years, considering an average raise of 5% in your kWh fee every year..
        /// </summary>
        internal static string financesMessage {
            get {
                return ResourceManager.GetString("financesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Energy coverage wanted:.
        /// </summary>
        internal static string formCoverage {
            get {
                return ResourceManager.GetString("formCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Price for kWh:.
        /// </summary>
        internal static string formFee {
            get {
                return ResourceManager.GetString("formFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Average money spent on energy by month:.
        /// </summary>
        internal static string formSpendings {
            get {
                return ResourceManager.GetString("formSpendings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Your monthly energy generation should look like this:.
        /// </summary>
        internal static string generationMessage {
            get {
                return ResourceManager.GetString("generationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Energy Generation.
        /// </summary>
        internal static string generationTitle {
            get {
                return ResourceManager.GetString("generationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Your region has an average of V1 kWh/(m².day). Based on this fact, and with your energy bill, we will calculate the viability of solar power where you live..
        /// </summary>
        internal static string ghiMessage {
            get {
                return ResourceManager.GetString("ghiMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This App will help you with investigating solar power viability close to your area. To achieve this, we are going to use your location and your energy bill. Please read the about page for further information..
        /// </summary>
        internal static string homeMessage {
            get {
                return ResourceManager.GetString("homeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This pie chart illustrates the total financial return after 25 years..
        /// </summary>
        internal static string pieChartMessage {
            get {
                return ResourceManager.GetString("pieChartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total Return.
        /// </summary>
        internal static string pieChartTitle {
            get {
                return ResourceManager.GetString("pieChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Your monthly revenue will vary according to your power generation:.
        /// </summary>
        internal static string revenueMessage {
            get {
                return ResourceManager.GetString("revenueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Revenue.
        /// </summary>
        internal static string revenueTitle {
            get {
                return ResourceManager.GetString("revenueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Begin!.
        /// </summary>
        internal static string startMessage {
            get {
                return ResourceManager.GetString("startMessage", resourceCulture);
            }
        }
    }
}
